# 🚀 Assignment 1 — Dataset Load + Understanding

👉 Hum sirf ye kaam karenge:

Dataset load

First rows dekhna

Shape check

Columns check

Data types check

Missing values check

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('pandas_main_sales_dataset.csv')
df.head()

,Order_ID,Customer_ID,Customer_Name,City,Category,Product,Order_Date,Sales,Profit,Quantity
0,1001,251,Priya,Bangalore,Clothing,T-shirt,2022-01-01,1071,NaN,5
1,1002,292,Ravi,Mumbai,Furniture,Chair,2022-01-02,4131,558.0,2
2,1003,214,Neha,Delhi,Electronics,T-shirt,2022-01-03,1620,278.0,3
3,1004,271,Arjun,Bangalore,Furniture,Chair,2022-01-04,741,1099.0,4
4,1005,260,Sneha,Lucknow,Electronics,Table,2022-01-05,4397,-7.0,7

In [4]:
df.dtypes

Order_ID           int64
Customer_ID        int64
Customer_Name     object
City              object
Category          object
Product           object
Order_Date        object
Sales              int64
Profit           float64
Quantity           int64
dtype: object

In [5]:
df.shape

(500, 10)

In [6]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Name', 'City', 'Category',
       'Product', 'Order_Date', 'Sales', 'Profit', 'Quantity'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       500 non-null    int64
 1   Customer_ID    500 non-null    int64
 2   Customer_Name  500 non-null    object
 3   City           475 non-null    object
 4   Category       500 non-null    object
 5   Product        500 non-null    object
 6   Order_Date     500 non-null    object
 7   Sales          500 non-null    int64
 8   Profit         475 non-null    float64
 9   Quantity       500 non-null    int64
dtypes: float64(1), int64(4), object(5)
memory usage: 39.2+ KB

In [8]:
df.describe()

          Order_ID  Customer_ID        Sales       Profit    Quantity
count   500.000000    500.00000   500.000000   475.000000  500.000000
mean   1250.500000    248.87400  2665.884000   558.892632    5.110000
std     144.481833     29.56983  1254.004313   575.353367    2.582099
min    1001.000000    200.00000   507.000000  -500.000000    1.000000
25%    1125.750000    223.00000  1561.000000    55.000000    3.000000
50%    1250.500000    250.00000  2675.000000   607.000000    5.000000
75%    1375.250000    272.25000  3722.000000  1067.500000    7.000000
max    1500.000000    299.00000  4994.000000  1498.000000    9.000000

In [9]:
print("\nMissing Values:")
print(df.isnull().sum())

Missing Values:
Order_ID          0
Customer_ID       0
Customer_Name     0
City             25
Category          0
Product           0
Order_Date        0
Sales             0
Profit           25
Quantity          0
dtype: int64

In [10]:
import pandas as pd

# Load dataset
df = pd.read_csv("pandas_main_sales_dataset.csv")

# First rows
print(df.head())

# Shape
print("Shape:", df.shape)

# Columns
print("Columns:", df.columns)

# Data types
print("Data Types:\n", df.dtypes)

# Info
print("\nDataset Info:")
df.info()

# Missing values
print("\nMissing Values:")
print(df.isnull().sum())

   Order_ID  Customer_ID Customer_Name       City     Category  Product  \
0      1001          251         Priya  Bangalore     Clothing  T-shirt
1      1002          292          Ravi     Mumbai    Furniture    Chair
2      1003          214          Neha      Delhi  Electronics  T-shirt
3      1004          271         Arjun  Bangalore    Furniture    Chair
4      1005          260         Sneha    Lucknow  Electronics    Table

   Order_Date  Sales  Profit  Quantity
0  2022-01-01   1071     NaN         5
1  2022-01-02   4131   558.0         2
2  2022-01-03   1620   278.0         3
3  2022-01-04    741  1099.0         4
4  2022-01-05   4397    -7.0         7
Shape: (500, 10)
Columns: Index(['Order_ID', 'Customer_ID', 'Customer_Name', 'City', 'Category',
       'Product', 'Order_Date', 'Sales', 'Profit', 'Quantity'],
      dtype='object')
Data Types:
 Order_ID           int64
Customer_ID        int64
Customer_Name     object
City              object
Category          object
Product           object
Order_Date        object
Sales              int64
Profit           float64
Quantity           int64
dtype: object

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       500 non-null    int64
 1   Customer_ID    500 non-null    int64
 2   Customer_Name  500 non-null    object
 3   City           475 non-null    object
 4   Category       500 non-null    object
 5   Product        500 non-null    object
 6   Order_Date     500 non-null    object
 7   Sales          500 non-null    int64
 8   Profit         475 non-null    float64
 9   Quantity       500 non-null    int64
dtypes: float64(1), int64(4), object(5)
memory usage: 39.2+ KB

Missing Values:
Order_ID          0
Customer_ID       0
Customer_Name     0
City             25
Category          0
Product           0
Order_Date        0
Sales             0
Profit           25
Quantity          0
dtype: int64

# 🎯 Assignment 2 Summary

Tumne seekha:

✔ Missing values detect
✔ Text column clean
✔ Numeric column clean
✔ Duplicate remove

## City Column Clean Karna

🔎 Explanation

👉 mode() → most common city

👉 [0] → first value

👉 fillna() → missing value replace karta hai

👉 inplace=True → original dataframe update karega

In [11]:
df["City"].fillna(df["City"].mode()[0], inplace=True)       # mode() → most common city, [0] → first value, fillna() → missing value replace karta hai, inplace=True → original dataframe update karega
print(df.head(5))

   Order_ID  Customer_ID Customer_Name       City     Category  Product  \
0      1001          251         Priya  Bangalore     Clothing  T-shirt
1      1002          292          Ravi     Mumbai    Furniture    Chair
2      1003          214          Neha      Delhi  Electronics  T-shirt
3      1004          271         Arjun  Bangalore    Furniture    Chair
4      1005          260         Sneha    Lucknow  Electronics    Table

   Order_Date  Sales  Profit  Quantity
0  2022-01-01   1071     NaN         5
1  2022-01-02   4131   558.0         2
2  2022-01-03   1620   278.0         3
3  2022-01-04    741  1099.0         4
4  2022-01-05   4397    -7.0         7

C:\Users\adadi\AppData\Local\Temp\ipykernel_3028\933458763.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["City"].fillna(df["City"].mode()[0], inplace=True)       # mode() → most common city, [0] → first value, fillna() → missing value replace karta hai, inplace=True → original dataframe update karega

## Profit Column Clean Karna

Profit numeric column hai.

Best practice:
👉 Mean ya Median se fill karte hain.

🔎 Explanation

👉 mean() → average profit

👉 Missing profit values ko average se replace kar diya

In [12]:
df["Profit"].fillna(df["Profit"].mean(), inplace=True)
print(df.head(5))

   Order_ID  Customer_ID Customer_Name       City     Category  Product  \
0      1001          251         Priya  Bangalore     Clothing  T-shirt
1      1002          292          Ravi     Mumbai    Furniture    Chair
2      1003          214          Neha      Delhi  Electronics  T-shirt
3      1004          271         Arjun  Bangalore    Furniture    Chair
4      1005          260         Sneha    Lucknow  Electronics    Table

   Order_Date  Sales       Profit  Quantity
0  2022-01-01   1071   558.892632         5
1  2022-01-02   4131   558.000000         2
2  2022-01-03   1620   278.000000         3
3  2022-01-04    741  1099.000000         4
4  2022-01-05   4397    -7.000000         7

C:\Users\adadi\AppData\Local\Temp\ipykernel_3028\2644292507.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Profit"].fillna(df["Profit"].mean(), inplace=True)

### check again : Is missing values occur

In [13]:
df.isnull().sum()

Order_ID         0
Customer_ID      0
Customer_Name    0
City             0
Category         0
Product          0
Order_Date       0
Sales            0
Profit           0
Quantity         0
dtype: int64

In [14]:
df.duplicated().sum()       # np.int64(0) iska matlab hai ki koi duplicate rows nahi hai aur agar hoti to np.int64(1) ya usse zyada hoti to iska matlab hota ki duplicate rows hai.

np.int64(0)

In [15]:
df.drop_duplicates(inplace=True)    # Duplicate Remove (Agar Mile)

In [16]:
df.info()       # Final Clean Dataset Check

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       500 non-null    int64
 1   Customer_ID    500 non-null    int64
 2   Customer_Name  500 non-null    object
 3   City           500 non-null    object
 4   Category       500 non-null    object
 5   Product        500 non-null    object
 6   Order_Date     500 non-null    object
 7   Sales          500 non-null    int64
 8   Profit         500 non-null    float64
 9   Quantity       500 non-null    int64
dtypes: float64(1), int64(4), object(5)
memory usage: 39.2+ KB

#  🎯 Assignment 3  — Filtering & Selection

👉 Filtering ka matlab hota hai:

Dataset me se specific records nikalna

Ye Data Analyst ka daily kaam hota hai.

### Task 1: Lucknow city orders

In [17]:
lucknow_order = df[df["City"] == "Lucknow"]        # df[df["City"] == "Lucknow"] → filter karega dataframe ko jisme city column ka value "Lucknow" hai, aur usko lucknow_order variable me store karega.
print(lucknow_order.head())

    Order_ID  Customer_ID Customer_Name     City     Category  Product  \
4       1005          260         Sneha  Lucknow  Electronics    Table
11      1012          299         Sneha  Lucknow    Furniture  T-shirt
12      1013          223         Sneha  Lucknow    Furniture   Mobile
20      1021          201         Priya  Lucknow     Clothing    Table
22      1023          259         Sneha  Lucknow    Furniture    Table

    Order_Date  Sales  Profit  Quantity
4   2022-01-05   4397    -7.0         7
11  2022-01-12   4526   799.0         1
12  2022-01-13   2747  1392.0         1
20  2022-01-21   4682   847.0         6
22  2022-01-23   4006   476.0         3

### Task 2: Sales > 3000 Orders

In [18]:
high_sales = df[df["Sales"] > 3000]
print(high_sales.head())

    Order_ID  Customer_ID Customer_Name     City     Category  Product  \
1       1002          292          Ravi   Mumbai    Furniture    Chair
4       1005          260         Sneha  Lucknow  Electronics    Table
5       1006          220          Amit   Mumbai  Electronics    Chair
9       1010          274         Arjun   Mumbai     Clothing    Table
11      1012          299         Sneha  Lucknow    Furniture  T-shirt

    Order_Date  Sales  Profit  Quantity
1   2022-01-02   4131   558.0         2
4   2022-01-05   4397    -7.0         7
5   2022-01-06   4595  1085.0         3
9   2022-01-10   3349   848.0         1
11  2022-01-12   4526   799.0         1

### Task 3 : Loss making Order

In [19]:
loss_order = df[df["Profit"] < 0]
print(loss_order.head())

    Order_ID  Customer_ID Customer_Name       City     Category Product  \
4       1005          260         Sneha    Lucknow  Electronics   Table
23      1024          220         Sneha    Lucknow    Furniture  Laptop
25      1026          275          Ravi  Bangalore    Furniture  Mobile
29      1030          248         Priya    Lucknow  Electronics   Table
33      1034          291          Ravi      Delhi  Electronics  Laptop

    Order_Date  Sales  Profit  Quantity
4   2022-01-05   4397    -7.0         7
23  2022-01-24    907   -19.0         6
25  2022-01-26   3588   -21.0         2
29  2022-01-30   4397  -158.0         8
33  2022-02-03   4994   -63.0         2

### Task 4 : Multiple conditions filtering

In [20]:
filtered_data = df[(df["City"] == "Lucknow") & (df["Sales"] > 3000)]
print(filtered_data.head())

    Order_ID  Customer_ID Customer_Name     City     Category  Product  \
4       1005          260         Sneha  Lucknow  Electronics    Table
11      1012          299         Sneha  Lucknow    Furniture  T-shirt
20      1021          201         Priya  Lucknow     Clothing    Table
22      1023          259         Sneha  Lucknow    Furniture    Table
29      1030          248         Priya  Lucknow  Electronics    Table

    Order_Date  Sales  Profit  Quantity
4   2022-01-05   4397    -7.0         7
11  2022-01-12   4526   799.0         1
20  2022-01-21   4682   847.0         6
22  2022-01-23   4006   476.0         3
29  2022-01-30   4397  -158.0         8

### Task 5 : Select specific columns

In [21]:
selected_clm = df[['Customer_Name', "Sales", "Profit"]]
print(selected_clm.head())

  Customer_Name  Sales       Profit
0         Priya   1071   558.892632
1          Ravi   4131   558.000000
2          Neha   1620   278.000000
3         Arjun    741  1099.000000
4         Sneha   4397    -7.000000

# 🚀 Assignment 4 : GroupBy Analytics

GroupBy: Divide the data into Category, and perform calculations on them

### Task 1 - Category wise total sales

In [22]:
category_sales = df.groupby('Category')['Sales'].sum()
print(category_sales)

Category
Clothing       422129
Electronics    471978
Furniture      438835
Name: Sales, dtype: int64

In [23]:
category_saless = df.groupby('Category').count()
print(category_saless)

             Order_ID  Customer_ID  Customer_Name  City  Product  Order_Date  \
Category
Clothing          156          156            156   156      156         156
Electronics       173          173            173   173      173         173
Furniture         171          171            171   171      171         171

             Sales  Profit  Quantity
Category
Clothing       156     156       156
Electronics    173     173       173
Furniture      171     171       171

### Task 2 - City Wise Average profit

In [24]:
city_prft = df.groupby('City')['Profit'].mean()
print(city_prft)

City
Bangalore    599.922180
Delhi        567.076940
Lucknow      502.813200
Mumbai       615.147998
Pune         531.485110
Name: Profit, dtype: float64

### Task 4 - Multiple aggregations

In [25]:
category_analysis = df.groupby('Category').agg({
    "Sales": 'sum',
    "Profit": 'mean',
    "Quantity": 'sum'
})

print(category_analysis)

              Sales      Profit  Quantity
Category
Clothing     422129  610.290054       826
Electronics  471978  505.612291       857
Furniture    438835  565.907258       872

### Task 5: Multi Column groupby

In [26]:
city_category_sales = df.groupby(['City', 'Category'])['Sales'].sum()
print(city_category_sales)

City       Category
Bangalore  Clothing        78166
           Electronics     48343
           Furniture       86951
Delhi      Clothing        72656
           Electronics     94599
           Furniture       80467
Lucknow    Clothing        97028
           Electronics    120995
           Furniture      111355
Mumbai     Clothing        86368
           Electronics    102681
           Furniture       83704
Pune       Clothing        87911
           Electronics    105360
           Furniture       76358
Name: Sales, dtype: int64

### Task 6: Reset Index

In [27]:
city_category_sales = city_category_sales.reset_index()
print(city_category_sales.head())

        City     Category  Sales
0  Bangalore     Clothing  78166
1  Bangalore  Electronics  48343
2  Bangalore    Furniture  86951
3      Delhi     Clothing  72656
4      Delhi  Electronics  94599

# 🚀 Assgnment 5 : Pivote Tables

### Task 1: City VS Category Sales Report

In [28]:
pivot_city_category = pd.pivot_table(
    df, 
    values='Sales',     # ➡ Sales ka calculation kar rahe hain
    index='City',       # ➡ Rows me city
    columns='Category', # ➡ Columns me category
    aggfunc='sum'       # ➡ Total sales calculate
)
print(pivot_city_category)

Category   Clothing  Electronics  Furniture
City
Bangalore     78166        48343      86951
Delhi         72656        94599      80467
Lucknow       97028       120995     111355
Mumbai        86368       102681      83704
Pune          87911       105360      76358

### Task 2: Month vs Product sales

In [29]:
df["Month"] = pd.to_datetime(df["Order_Date"]).dt.month         # Date ko datetime me convert kiya, Month extract kiya

In [30]:
pivot_month_product = pd.pivot_table(
    df,
    values="Sales",
    index="Month",
    columns="Product",
    aggfunc="sum"
)
print(pivot_month_product)

Product  Chair  Laptop  Mobile  T-shirt  Table
Month
1        29153   27221   38033    32577  41050
2        32143   23745   24878    32079  43038
3        31142   30143   50790    19623  30865
4        45992   27971   26920    17583  49570
5        25998   39270   15397    17013  19127
6         8676    2523   22351    25448  27915
7        18609   18310   18412     5654  18251
8        29080   15111   12059    12143   8711
9        10317   19465    4603    14966  18445
10       16778    9511   34562    11737  13672
11        8653   19116   32349     3633  21047
12       24068   16456   14337    18392   6261

### TASK 3 — Multiple Values Pivot

In [31]:
multi_pivot = pd.pivot_table(
    df,
    values=["Sales", "Profit"],
    index="Category",
    aggfunc=["sum", "mean"]
)

print(multi_pivot)

                      sum                mean
                   Profit   Sales      Profit        Sales
Category
Clothing     95205.248421  422129  610.290054  2705.955128
Electronics  87470.926316  471978  505.612291  2728.196532
Furniture    96770.141053  438835  565.907258  2566.286550

### TASK 4 — Pivot Table With Total

In [32]:
pivot_with_total = pd.pivot_table(
    df,
    values="Sales",
    index="City",
    columns="Category",
    aggfunc="sum",
    margins=True        # ➡ Grand total add karta hai
)

print(pivot_with_total)

Category   Clothing  Electronics  Furniture      All
City
Bangalore     78166        48343      86951   213460
Delhi         72656        94599      80467   247722
Lucknow       97028       120995     111355   329378
Mumbai        86368       102681      83704   272753
Pune          87911       105360      76358   269629
All          422129       471978     438835  1332942

### TASK 5 — Missing Values Handle In Pivot

In [33]:
pivot_filled = pd.pivot_table(
    df,
    values="Sales",
    index="City",
    columns="Category",
    aggfunc="sum",
    fill_value=0        # Missing values ko 0 se fill karta hai
)

print(pivot_filled)

Category   Clothing  Electronics  Furniture
City
Bangalore     78166        48343      86951
Delhi         72656        94599      80467
Lucknow       97028       120995     111355
Mumbai        86368       102681      83704
Pune          87911       105360      76358

# 🚀 Assignment 6 — Feature Engineering

## 🧠 Feature Engineering Kya Hota Hai?

```
Existing data se new useful columns banana
```

Example:

* Profit Margin
* Order Size Category
* Customer Type
* Sales per Unit

### TASK 1 — Profit Margin Column Banana 
Formula:

```
Profit Margin = Profit / Sales
```

In [34]:
df["Profit_Margin"] = df["Profit"] / df["Sales"]

print(df[["Sales", "Profit", "Profit_Margin"]].head())

   Sales       Profit  Profit_Margin
0   1071   558.892632       0.521842
1   4131   558.000000       0.135076
2   1620   278.000000       0.171605
3    741  1099.000000       1.483131
4   4397    -7.000000      -0.001592

In [35]:
df.columns

Index(['Order_ID', 'Customer_ID', 'Customer_Name', 'City', 'Category',
       'Product', 'Order_Date', 'Sales', 'Profit', 'Quantity', 'Month',
       'Profit_Margin'],
      dtype='object')

### TASK 2 — Sales per Unit
Formula:

```
Sales per Unit = Sales / Quantity
```

In [36]:
df["Sales_per_Unit"] = df["Sales"] / df["Quantity"]

print(df[["Sales", "Quantity", "Sales_per_Unit"]].head())

   Sales  Quantity  Sales_per_Unit
0   1071         5      214.200000
1   4131         2     2065.500000
2   1620         3      540.000000
3    741         4      185.250000
4   4397         7      628.142857

### TASK 3 — Order Value Category 

Hum order ko classify karenge:

| Sales     | Category |
| --------- | -------- |
| <1500     | Low      |
| 1500–3500 | Medium   |
| >3500     | High     |

In [37]:
def order_category(sales):
    if sales < 1500:
        return "Low"
    elif sales <= 3500:
        return "Medium"
    else:
        return "High"

df["Order_Category"] = df["Sales"].apply(order_category)        # apply() use karke har row par logic apply kiya

print(df[["Sales", "Order_Category"]].head())

   Sales Order_Category
0   1071            Low
1   4131           High
2   1620         Medium
3    741            Low
4   4397           High

### TASK 4 — Customer Total Spending

In [38]:
customer_total = df.groupby("Customer_Name")["Sales"].transform("sum")          # transform("sum"): Har customer ka total spending har row me add ho gaya

df["Customer_Total_Spending"] = customer_total

print(df[["Customer_Name", "Customer_Total_Spending"]].head())

  Customer_Name  Customer_Total_Spending
0         Priya                   204364
1          Ravi                   230889
2          Neha                   215210
3         Arjun                   260267
4         Sneha                   184606

### TASK 5 — Profit Type (Loss / Gain)

In [39]:
df["Profit_Type"] = df["Profit"].apply(lambda x: "Loss" if x < 0 else "Gain")

print(df[["Profit", "Profit_Type"]].head())

        Profit Profit_Type
0   558.892632        Gain
1   558.000000        Gain
2   278.000000        Gain
3  1099.000000        Gain
4    -7.000000        Loss

# 🚀 Assignment 7 — Time Series Analytics

### STEP 1 — Date Column Ko Proper Datetime Banana

In [40]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"])     # Date ko proper datetime format me convert kiya

print(df["Order_Date"].dtype)

datetime64[ns]

### STEP 2 — Year, Month, Day Extract Karna

In [41]:
df["Year"] = df["Order_Date"].dt.year
df["Month"] = df["Order_Date"].dt.month
df["Day"] = df["Order_Date"].dt.day
df["Weekday"] = df["Order_Date"].dt.day_name()

print(df[["Order_Date","Year","Month","Weekday"]].head())

  Order_Date  Year  Month    Weekday
0 2022-01-01  2022      1   Saturday
1 2022-01-02  2022      1     Sunday
2 2022-01-03  2022      1     Monday
3 2022-01-04  2022      1    Tuesday
4 2022-01-05  2022      1  Wednesday

### STEP 3 — Monthly Sales Trend

In [42]:
monthly_sales = df.groupby("Month")["Sales"].sum().reset_index()
print(monthly_sales)

    Month   Sales
0       1  168034
1       2  155883
2       3  162563
3       4  168036
4       5  116805
5       6   86913
6       7   79236
7       8   77104
8       9   67796
9      10   86260
10     11   84798
11     12   79514

### STEP 4 — Year Wise Profit Growth

In [43]:
yearly_profit = df.groupby("Year")["Profit"].sum().reset_index()

print(yearly_profit)

   Year         Profit
0  2022  206562.530526
1  2023   72883.785263

### STEP 5 — Weekday vs Weekend Analysis

In [44]:
df["Is_Weekend"] = df["Weekday"].isin(["Saturday","Sunday"])

weekend_analysis = df.groupby("Is_Weekend")["Sales"].mean().reset_index()

print(weekend_analysis)

   Is_Weekend        Sales
0       False  2668.952247
1        True  2658.298611

### STEP 6 — Resampling (Advanced Time Series)

In [45]:
df.set_index("Order_Date", inplace=True)

monthly_resample = df["Sales"].resample("M").sum()      # `resample("M")` ➡ Monthly grouping karta hai


print(monthly_resample.head())

Order_Date
2022-01-31    86957
2022-02-28    80792
2022-03-31    88392
2022-04-30    84325
2022-05-31    77950
Freq: ME, Name: Sales, dtype: int64

C:\Users\adadi\AppData\Local\Temp\ipykernel_3028\4141908912.py:3: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_resample = df["Sales"].resample("M").sum()      # `resample("M")` ➡ Monthly grouping karta hai

| Code | Meaning |
| ---- | ------- |
| "D"  | Daily   |
| "W"  | Weekly  |
| "M"  | Monthly |
| "Y"  | Yearly  |

# 🚀 Assignment 8 — Window Functions

## 🧠 Window Function Kya Hoti Hai?

Simple language:

```
Previous rows ko use karke calculation karna
```

Example:

👉 Running total
👉 Moving average
👉 Cumulative profit
👉 Ranking

---

### TASK 1 — Running Total Sales

In [46]:
df["Running_Sales"] = df["Sales"].cumsum()      

print(df[["Sales", "Running_Sales"]].head())

            Sales  Running_Sales
Order_Date
2022-01-01   1071           1071
2022-01-02   4131           5202
2022-01-03   1620           6822
2022-01-04    741           7563
2022-01-05   4397          11960

👉 `cumsum()`
➡ Cumulative sum banata hai

Example:

```
Sales → 100
Sales → 200
Sales → 300
```

Running total:

```
100
300
600
```

---

### TASK 2 — Cumulative Profit

In [47]:
df["Running_Profit"] = df["Profit"].cumsum()

print(df[["Profit", "Running_Profit"]].head())

                 Profit  Running_Profit
Order_Date
2022-01-01   558.892632      558.892632
2022-01-02   558.000000     1116.892632
2022-01-03   278.000000     1394.892632
2022-01-04  1099.000000     2493.892632
2022-01-05    -7.000000     2486.892632

### TASK 3 — Rolling Moving Average

In [48]:
df["Rolling_Sales_3"] = df["Sales"].rolling(3).mean()       # Last 3 rows ka average Trend analysis me use hota hai


print(df[["Sales", "Rolling_Sales_3"]].head())

            Sales  Rolling_Sales_3
Order_Date
2022-01-01   1071              NaN
2022-01-02   4131              NaN
2022-01-03   1620      2274.000000
2022-01-04    741      2164.000000
2022-01-05   4397      2252.666667

### TASK 4 — Expanding Window

In [49]:
df["Expanding_Sales"] = df["Sales"].expanding().mean()

print(df[["Sales", "Expanding_Sales"]].head())

            Sales  Expanding_Sales
Order_Date
2022-01-01   1071          1071.00
2022-01-02   4131          2601.00
2022-01-03   1620          2274.00
2022-01-04    741          1890.75
2022-01-05   4397          2392.00

### TASK 5 — Ranking

In [50]:
df["Sales_Rank"] = df["Sales"].rank(ascending=False)

print(df[["Sales", "Sales_Rank"]].head())

            Sales  Sales_Rank
Order_Date
2022-01-01   1071       442.0
2022-01-02   4131        89.0
2022-01-03   1620       368.0
2022-01-04    741       482.0
2022-01-05   4397        56.5

### TASK 6 — Group Wise Running Total

In [51]:
df["Category_Running_Sales"] = df.groupby("Category")["Sales"].cumsum()

print(df[["Category", "Sales", "Category_Running_Sales"]].head())

               Category  Sales  Category_Running_Sales
Order_Date
2022-01-01     Clothing   1071                    1071
2022-01-02    Furniture   4131                    4131
2022-01-03  Electronics   1620                    1620
2022-01-04    Furniture    741                    4872
2022-01-05  Electronics   4397                    6017

# 🚀 Pandas Data Save Karna

In [52]:
df.to_csv("final_sales_dataset.csv", index=False)

Bahut badhiya 👍 Agar tumne saare tasks perform kar liye hain, to **final cleaned + processed dataset save karna** ek **real industry step** hota hai.

Main tumhe **saare important saving methods** samjha deta hoon.

---

# 🚀 Pandas Data Save Karna

Tum abhi final dataset use kar rahe ho:

👉 `df_final` (merged + cleaned + engineered dataset)

---

# ⭐ 1️⃣ CSV File Me Save Karna (Most Common)

## ✅ Code

```python
df_final.to_csv("final_sales_dataset.csv", index=False)
```

---

### 🔎 Explanation

👉 `"final_sales_dataset.csv"` → file ka naam
👉 `index=False` → extra index column save nahi karega

---

### 🎯 Output

Tumhare folder me file ban jayegi:

```
final_sales_dataset.csv
```

---

# ⭐ 2️⃣ Excel File Me Save Karna ⭐

Industry me Excel bhi use hota hai.

---

## ✅ Code

```python
df_final.to_excel("final_sales_dataset.xlsx", index=False)
```

---

👉 Ye Excel file bana dega.

---

# ⭐ 3️⃣ Multiple Sheets Excel Me Save Karna (Advanced + Useful)

Agar tum alag-alag reports save karna chaho:

---

## ✅ Code

```python
with pd.ExcelWriter("sales_report.xlsx") as writer:
    df_final.to_excel(writer, sheet_name="Full Data", index=False)
    supplier_analysis.to_excel(writer, sheet_name="Supplier Analysis")
    top_products.to_excel(writer, sheet_name="Top Products")
```

---

### 🔥 Industry Use

👉 Reporting automation me use hota hai.

---

# ⭐ 4️⃣ Specific Folder Me Save Karna

---

## ✅ Example

```python
df_final.to_csv("data/final_sales_dataset.csv", index=False)
```

👉 File `data` folder me save hogi.

---

# ⭐ 5️⃣ JSON Format Me Save Karna (ML / API Use)

---

## ✅ Code

```python
df_final.to_json("final_data.json")
```

---

# 🧠 Industry Best Practice

Mostly companies use:

```
CSV → Data storage
Excel → Reporting
Parquet → Big Data
```

---

# 🎯 Tumhare Case Me Best Save Option

👉 Excel + CSV dono save karo
👉 Resume / portfolio me useful hota hai

---

# ⭐ Recommended Final Save Code

```python
df_final.to_csv("final_sales_dataset.csv", index=False)
df_final.to_excel("final_sales_dataset.xlsx", index=False)
```

---

# 🚀 Bonus (Very Important Data Analyst Tip)

Save karne se pehle:

```python
df_final.shape
df_final.info()
```

👉 Confirm dataset properly clean hai.

---

# 🔥 Tumne Ab Tak Jo Kiya Hai

Tum practically kar chuke ho:

✔ End-to-end Pandas pipeline
✔ Multi dataset merging
✔ Feature engineering
✔ Time series analytics
✔ Business reporting

👉 Ye **resume worthy project** hai 🔥

---

# ⭐ Agar Tum Chaho

Main tumhare liye bana sakta hoon:

👉 Is project ka **resume project description**
👉 GitHub project structure
👉 Portfolio explanation
👉 Interview questions from this project

---

Bas ek sawal 👇
👉 Tum is dataset ko future me kis purpose ke liye use karna chahte ho?

1️⃣ Resume Project
2️⃣ Machine Learning Training
3️⃣ Dashboard (Power BI / Streamlit)
4️⃣ Portfolio Project

Batana 👍