In [1]:
import pandas as pd

## Roadmap

- creating dataset
    - dictionary of item 
    - lisk of dictionaries
    - importing dataset as CSV, xlsx etc. formats
- basic insights of dataset
- data selection
    - row wise selection 
    - column wise selection
- cleaning of manipulation

In [2]:
import pandas as pd
data = {
    "name": ['a','b','c','d'],
    "age": [20,21,19,18],
    "address": ['BBK','LKO','GDA','KP']
}
df = pd.DataFrame(data)
df  # isko print ke andar bhi likh sakte hai lekin uske andar likhne par excel wala theme(mzaa) nahi ayega

  name  age address
0    a   20     BBK
1    b   21     LKO
2    c   19     GDA
3    d   18      KP

## Read a CSV file

read_csv()

In [3]:
# when you want to read a file ten you can use read_csv('file path)
df = pd.read_csv('kc_house_data.csv')
df

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

## Data Selection and Indexing

In [4]:
df.head()   # display the first five data rows(by default until you not give any number )

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [5]:
df.tail()  # display the last first five data rows(by default until you not give any number )

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [6]:
df.sample() # display randomly row (by default until you not give any number)

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
178,5437810320,20141117T000000,269950.0,3,1.5,1950,7560,1.0,0,2,...,7,1320,630,1975,0,98022,47.1976,-121.999,1950,8941

In [7]:
df.info()   # give the describe summary of the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB

In [8]:
df.describe() # generate discriptive statisticsof the DataFram

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [9]:
df.isnull().sum()   # check for missing values in dataframe

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [10]:
df.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [11]:
df.columns.tolist()

['id',
 'date',
 'price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long',
 'sqft_living15',
 'sqft_lot15']

- row wise selection
    - iloc:  index based selection
    - loc : label based selection
- column wise selection
    - single column selection
        - dictionary like selection
        - object like selection
    - multiple like selection
        - dictionary like selection

In [12]:
df.iloc[45]

id                    8035350320
date             20140718T000000
price                   488000.0
bedrooms                       3
bathrooms                    2.5
sqft_living                 3160
sqft_lot                   13603
floors                       2.0
waterfront                     0
view                           0
condition                      3
grade                          8
sqft_above                  3160
sqft_basement                  0
yr_built                    2003
yr_renovated                   0
zipcode                    98019
lat                      47.7443
long                    -121.977
sqft_living15               3050
sqft_lot15                  9232
Name: 45, dtype: object

In [13]:
df.iloc[2:7]    # show table from 2 to 6

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
5,7237550310,20140512T000000,1225000.0,4,4.50,5420,101930,1.0,0,0,...,11,3890,1530,2001,0,98053,47.6561,-122.005,4760,101930
6,1321400060,20140627T000000,257500.0,3,2.25,1715,6819,2.0,0,0,...,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819

In [14]:
df.iloc[2:7:2]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
6,1321400060,20140627T000000,257500.0,3,2.25,1715,6819,2.0,0,0,...,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819

In [15]:
df.iloc[[2,8,6,9]]

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
8,2414600126,20150415T000000,229500.0,3,1.00,1780,7470,1.0,0,0,...,7,1050,730,1960,0,98146,47.5123,-122.337,1780,8113
6,1321400060,20140627T000000,257500.0,3,2.25,1715,6819,2.0,0,0,...,7,1715,0,1995,0,98003,47.3097,-122.327,2238,6819
9,3793500160,20150312T000000,323000.0,3,2.50,1890,6560,2.0,0,0,...,7,1890,0,2003,0,98038,47.3684,-122.031,2390,7570

In [16]:
df.iloc[[2,4,5,6],[1,2,3,4]]

              date      price  bedrooms  bathrooms
2  20150225T000000   180000.0         2       1.00
4  20150218T000000   510000.0         3       2.00
5  20140512T000000  1225000.0         4       4.50
6  20140627T000000   257500.0         3       2.25

In [17]:
# here is 'id' set as a index
df = df.set_index('id')
df

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [18]:
df.loc[6414100192]

date             20141209T000000
price                   538000.0
bedrooms                       3
bathrooms                   2.25
sqft_living                 2570
sqft_lot                    7242
floors                       2.0
waterfront                     0
view                           0
condition                      3
grade                          7
sqft_above                  2170
sqft_basement                400
yr_built                    1951
yr_renovated                1991
zipcode                    98125
lat                       47.721
long                    -122.319
sqft_living15               1690
sqft_lot15                  7639
Name: 6414100192, dtype: object

In [19]:
df.loc[[6414100192,263000018]]

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509

In [20]:
df.sort_index() # sort by index

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
1000102,20150422T000000,300000.0,6,3.00,2400,9373,2.0,0,0,3,7,2400,0,1991,0,98002,47.3262,-122.214,2060,7316
1000102,20140916T000000,280000.0,6,3.00,2400,9373,2.0,0,0,3,7,2400,0,1991,0,98002,47.3262,-122.214,2060,7316
1200019,20140508T000000,647500.0,4,1.75,2060,26036,1.0,0,0,4,8,1160,900,1947,0,98166,47.4444,-122.351,2590,21891
1200021,20140811T000000,400000.0,3,1.00,1460,43000,1.0,0,0,3,7,1460,0,1952,0,98166,47.4434,-122.347,2250,20023
2800031,20150401T000000,235000.0,3,1.00,1430,7599,1.5,0,0,4,6,1010,420,1930,0,98168,47.4783,-122.265,1290,10320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9842300095,20140725T000000,365000.0,5,2.00,1600,4168,1.5,0,0,3,7,1600,0,1927,0,98126,47.5297,-122.381,1190,4168
9842300485,20150311T000000,380000.0,2,1.00,1040,7372,1.0,0,0,5,7,840,200,1939,0,98126,47.5285,-122.378,1930,5150
9842300540,20140624T000000,339000.0,3,1.00,1100,4128,1.0,0,0,4,7,720,380,1942,0,98126,47.5296,-122.379,1510,4538
9895000040,20140703T000000,399900.0,2,1.75,1410,1005,1.5,0,0,3,9,900,510,2011,0,98027,47.5446,-122.018,1440,1188
9900000190,20141030T000000,268950.0,3,1.00,1320,8100,1.0,0,0,3,6,880,440,1943,0,98166,47.4697,-122.351,1000,8100

## Data Cleaning

### Handling missing data:

In [21]:
df.isnull()     # agar koi null value nahi hai to waha par true return karega nahi to false return karega

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6414100192,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5631500400,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2487200875,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1954400510,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6600060120,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1523300141,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
291310100,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1523300157,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [22]:
df.notnull()    # agar koi null value hai to waha par true return karega

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
6414100192,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
5631500400,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
2487200875,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1954400510,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
6600060120,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1523300141,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
291310100,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
1523300157,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

In [23]:
df.dropna()     # missing (NaN) value ko hata deta hai DataFrame/Series

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [24]:
df.fillna(0)    # missing (NaN) value ko replace kar(bracket me likhe value se) deta hai

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [25]:
df.drop_duplicates()    # it remove duplicate value

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
id,,,,,,,,,,,,,,,,,,,,
7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

## Data Transformtion

In [26]:
data = {
    "A": [1,2,3,4],
    "B": [20,21,19,23 ]
}
ad = pd.DataFrame(data)
ad   # isko print ke andar bhi likh sakte hai lekin uske andar likhne par excel wala theme(mzaa) nahi ayega

   A   B
0  1  20
1  2  21
2  3  19
3  4  23

__apply()__ --> Row/Column level functionapply karta hai.</br>
__applmap()__--> DataFrame ke har ek element ke function apply karta hai</br>
__lambda__ --> Ek anonymous (one-line) function likhne ka shortcut. iska use mainly apply()</br>
__replace__ --> Specific value ko dusri value se replace karta hai </br>

In [27]:
# use apply()
ad['A'] = ad['A'].apply(lambda x: x ** 2)
ad

    A   B
0   1  20
1   4  21
2   9  19
3  16  23

In [28]:
# use applymap()
ad = ad.applymap(lambda x: x ** 2)
ad

C:\Users\adadi\AppData\Local\Temp\ipykernel_20136\1673441465.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  ad = ad.applymap(lambda x: x ** 2)

     A    B
0    1  400
1   16  441
2   81  361
3  256  529

In [29]:
# Lambda 
square = lambda x: x ** 2
print(square(5))

25

In [30]:
# replace
ad['A'] = ad['A'].replace(16, 32)
ad

     A    B
0    1  400
1   32  441
2   81  361
3  256  529

## Grouping and aggeresion in pandas

#### __groupby() basic__ --> Kisi column ke basis par data ko group karna

In [31]:
# groupby() basic 
import pandas as pd

data = {
    "name": ['a','b','c','d'],
    "salary": [20000,21000,19000,18000]
}
fd = pd.DataFrame(data)
print(fd.groupby('name')['salary'].mean())

name
a    20000.0
b    21000.0
c    19000.0
d    18000.0
Name: salary, dtype: float64

#### __Aggregation (mean, sum, count...etc)__ --> Group ke uper summary function lagana

In [32]:
fd.groupby('name')['salary'].mean().max()

np.float64(21000.0)

In [33]:
fd.groupby('name')['salary'].mean().count()

np.int64(4)

In [34]:
fd.groupby('name')['salary'].mean().sum()

np.float64(78000.0)

#### __agg()__ for multiple function apply karne ke liye
- ek hi column par multiple function apply karna

In [35]:
fd.groupby('name')['salary'].agg(['mean','sum','max'])

         mean    sum    max
name
a     20000.0  20000  20000
b     21000.0  21000  21000
c     19000.0  19000  19000
d     18000.0  18000  18000

#### Multi-level grouping
- ek se zyada columns ke basis par grouping

In [36]:
import pandas as pd

data = {
    "name": ['a','b','c','d'],
    'gender': ['M','F','M','M'],
    "salary": [20000,21000,19000,18000]
}
cd = pd.DataFrame(data)
print(cd.groupby(['name','gender'])['salary'].mean())

name  gender
a     M         20000.0
b     F         21000.0
c     M         19000.0
d     M         18000.0
Name: salary, dtype: float64

#### Pivot tables & crosstab
- Excel jaise sumary table banane ke liye

__'_Pivot table_'__

In [37]:
# Pivot table
print(cd.pivot_table(values='salary', index='name', columns='gender',aggfunc="mean"))

gender        F        M
name
a           NaN  20000.0
b       21000.0      NaN
c           NaN  19000.0
d           NaN  18000.0

__'_Crosstab ( frequency count )_'__

In [38]:
print(pd.crosstab(cd['name'],cd['gender']))

gender  F  M
name
a       0  1
b       1  0
c       0  1
d       0  1

## Merging & Joining in Pandas

#### Concaenation --> pd.concat()
- DataFrame ko row wise ya colunm wise jodna

In [39]:
import pandas as pd

df1 = pd.DataFrame({"ID": [1, 2], "Name": ["A", "B"]})
df2 = pd.DataFrame({"ID": [3, 4], "Name": ["C", "D"]})

# Row-wise concat
print(pd.concat([df1, df2]))

# Column-wise concat
print(pd.concat([df1, df2], axis=1))

   ID Name
0   1    A
1   2    B
0   3    C
1   4    D
   ID Name  ID Name
0   1    A   3    C
1   2    B   4    D

#### Merge --> pd.merge()
- SQL JOIN ki tarah kamm karta hai (common column ke basis par)

In [40]:
employees = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["A", "B", "C"]
})

salary = pd.DataFrame({
    "ID": [1, 2, 4],
    "Salary": [50000, 60000, 70000]
})

# Default: INNER JOIN
print(pd.merge(employees, salary, on="ID"))

# LEFT JOIN
print(pd.merge(employees, salary, on="ID", how="left"))

# RIGHT JOIN
print(pd.merge(employees, salary, on="ID", how="right"))

# OUTER JOIN
print(pd.merge(employees, salary, on="ID", how="outer"))

   ID Name  Salary
0   1    A   50000
1   2    B   60000
   ID Name   Salary
0   1    A  50000.0
1   2    B  60000.0
2   3    C      NaN
   ID Name  Salary
0   1    A   50000
1   2    B   60000
2   4  NaN   70000
   ID Name   Salary
0   1    A  50000.0
1   2    B  60000.0
2   3    C      NaN
3   4  NaN  70000.0

➡ Types of Joins:

INNER JOIN → Common values only

LEFT JOIN → Left DataFrame ke sab + matching right

RIGHT JOIN → Right DataFrame ke sab + matching left

OUTER JOIN → Dono ke sab values (missing = NaN)

#### ✅ (3) Join → df.join()

- 👉 Mostly index ke basis par join karta hai.

In [41]:

df3 = pd.DataFrame({"Name": ["A", "B", "C"]}, index=[1,2,3])
df4 = pd.DataFrame({"Salary": [50000, 60000, 70000]}, index=[1,2,3])

print(df3.join(df4))

  Name  Salary
1    A   50000
2    B   60000
3    C   70000

#### ✅ (4) One-to-One, One-to-Many, Many-to-Many

- One-to-One → Ek row match karta hai dusre ek row se.

- One-to-Many → Ek row match hota hai multiple rows se.

- Many-to-Many → Dono taraf multiple matches ho sakte hain.

#### ⚡Short Summary:

- concat() → DataFrames ko row/column wise jodna

- merge() → SQL join jaisa (on = column)

- join() → Mostly index ke basis par join

- Supports INNER, LEFT, RIGHT, OUTER joins